name: Go

on:
  push:
    branches: ["*"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19.x", "1.20.x"]
        include:
          - go: 1.20.x
            latest: true

    steps:
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load cached dependencies
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install
        run: make install

      - name: Lint
        if: matrix.latest
        uses: golangci/golangci-lint-action@v3

      - name: Test
        run: make cover

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v3
